### ISSUE TITLE
Git hub actions

### ISSUE THREAD

**Issue by parzival3** [johannesmols/MBSE-Project-Group-7#6]
I really want to make this work

**Comment by parzival3** [comment]
@johannesmols what is this secrete here?
https://github.com/johannesmols/MBSE-Project-Group-7/actions/runs/261666595/workflow#L12
Do you have the source of this action? All my test failed because I cannot decrypt the key

**Comment by johannesmols** [comment]
@parzival3 ah damn I deleted it again. I created it by following this tutorial: https://youtu.be/-txXtAfViEQ
Also make sure to set the right version in the YML file. The latest Unity version is 2020.1.6f1

**Comment by parzival3** [comment]
@johannesmols fake it until you make it :laughing: :rofl: ... I've used the workflow file from this guy here https://github.com/webbertakken/unity-actions/, and I've also copied his project in our project to make it build otherwise it was failing, but now we have something that builds on every commit. It takes quite a lot of time, so maybe we need to change the setting in the yml file to run all the build nightly and run only windows build per commit.. anyway we made it work. Do you think we can start fresh from this project, or is it a problem?.  The second question, as for now, I'm building with the Unity license of the guy, I think we should create a new license and create a new secret as you did :smiley: but I think this is just a small problem.

**Comment by johannesmols** [comment]
@parzival3 lol good job. I also tried that one before but couldn't get it to work. I'd rather not touch the license if it works like that, but it is still running on a 2019 version. I'll try and see what happens if i run it with the latest version. I guess we can remove OS X, iOS, ... for now but the build time really doesn't matter that much. And in the end, this is just a nice to have anyway, we can also just build it ourselves :) we should probably create a model first 😆 about the project I'm not really sure what all that stuff in there is but I will give it a try to remove some of it and see what happens.

**Comment by johannesmols** [comment]
@parzival3 I'm starting to lose hope on this. As soon as I updated to the latest version it sometimes failed, sometimes worked, but the build artifact was always 0 bytes. I have no idea why. I also tried creating my own license using this: https://github.com/marketplace/actions/unity-request-activation-file but then the test run fails without any kind of descriptive error... I think we should just stop at this point and focus on making a simulation instead of trying to get automated builds for something we will probably only build once xD
